---
title: "Hands-on examples on creating flow maps"
output: html_document
date: "2024-02-22"
editor_options: 
  chunk_output_type: console
---

```{r setup}
nyc_flights <- nycflights13::flights |>
  dplyr::filter(
    # discarding since airport location is not available
    !dest %in% c("BQN", "PSE", "SJU", "STT")
  )
airport_locations <- nycflights13::airports |>
  dplyr::filter(faa %in% unique(c(nyc_flights$origin, nyc_flights$dest))) |>
  dplyr::select(id = faa, name, lat, lon)

copy_clip <- function(data) {
  write.table(data, "clipboard-1024", quote = FALSE, sep = ",", row.names = FALSE)
}
```

## Demo 1: Create a flow map visualizing total flight trips originating from New York (NYC)

```{r nyc-flows}
nyc_flows <- nyc_flights |>
  dplyr::count(origin, dest, name = "count")
dplyr::glimpse(nyc_flows)
skimr::skim(nyc_flows)
```

## Demo 2: Create a flow map visualizing total flight trips originating from NYC in May

```{r nyc-flows-may}
nyc_flows_may <- nyc_flights |>
  dplyr::filter(month == 5) |>
  dplyr::count(origin, dest, name = "count")
dplyr::glimpse(nyc_flows_may)
skimr::skim(nyc_flows_may)
```

## Demo 3: Create a flow map visualizing monthly fluctuations in flight trips originating from NYC

```{r nyc-flows-monthly}
nyc_flows_monthly <- nyc_flights |>
  dplyr::mutate(
    time = lubridate::ym(glue::glue("{year}-{month}")),
    time = lubridate::format_ISO8601(time, precision = "ym")
  ) |>
  dplyr::count(origin, dest, time, name = "count") |>
  dplyr::relocate(time, .after = dplyr::last_col())
dplyr::glimpse(nyc_flows_monthly)

nyc_flows_monthly |>
  dplyr::group_by(time) |>
  skimr::skim()
```
